# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/luigi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),luigi)

$(call add-radio-file-sha1-checked,radio/abl.img,d4eb89a6d00832765fb8dc3399dcae782c61a48f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,02208eef75fd3f1a1aa7a3babe8c9babf3018a20)
$(call add-radio-file-sha1-checked,radio/core_nhlos.img,48c05993e852eb60adc47e5805c88a39c39e464d)
$(call add-radio-file-sha1-checked,radio/devcfg.img,544ca5bcb3bc300f79712e58700077a67f0dad01)
$(call add-radio-file-sha1-checked,radio/dsp.img,9606e98a9e1a1b886170e4858e7dc5ab2910548a)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,9091a7f9639d3cbe26ce83b3724d13afed1dfb2e)
$(call add-radio-file-sha1-checked,radio/hyp.img,c9f1a7bfe1a0188f54d4cc00e2b114bf70da6913)
$(call add-radio-file-sha1-checked,radio/imagefv.img,21b6df7bcda4056b4cf627f4c4d5b7a0815cc5ac)
$(call add-radio-file-sha1-checked,radio/keymaster.img,3e27a73be70cbdc3fc327dcfd06725c9e4adf0e3)
$(call add-radio-file-sha1-checked,radio/modem.img,4520bc5ba8b5d11602b89b6b5a887d57bb80cdc0)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,611818027635a560cf56f608943533a9560a7c50)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,fe323882421e1413729f31a2e6ddffbdf56705bc)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e7dece96eae7117598cf0e57d063b5d0595d98a2)
$(call add-radio-file-sha1-checked,radio/rpm.img,0fb8f622984c9e279c12a3760a87ec3b87636bca)
$(call add-radio-file-sha1-checked,radio/splash.img,abb85d2bfa3fa6e5e6e0028566c96e134cd39a38)
$(call add-radio-file-sha1-checked,radio/tz.img,41eba895d7cde260a8400dc6457a5a9fa2378b7f)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,8da4bff191c65ff8cca0b0f3bdf93984b9df2a02)
$(call add-radio-file-sha1-checked,radio/xbl.img,a5f16a0d860f29482bc6555147c42c3826a0dba2)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,772499f843e24e8b9f94b1788a99e9ca60e79523)

endif
